---
title: "GF-0604 Procesamiento de datos geográficos<br>Laboratorio 02: R - Graficación básica"
author: "Manuel Vargas"
date: "2020-04-20"
output:
  html_document:
    theme: readable    
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Descripción general
En este laboratorio, el estudiante

## Fecha de entrega y entregables
La fecha límite de entrega de este laboratorio es el **30 de abril de 2020**. Debe enviarle al profesor por correo electrónico la dirección de la página web resultante (ej. https://mfvargas.github.io/laboratorio-02-r-graficacion-basica/).

## Objetivos
Al finalizar este laboratorio, el estudiante será capaz de:

1. Bifurcar un repositorio en GitHub.
2. Clonar un repositorio mediante el protocolo Git y la interfaz de RStudio.
3. 

## Trabajo previo
Se recomienda leer el material preparado por el profesor y consultar los recursos listados en [Lección 04: El lenguaje de programación R - Introducción](https://geoprocesamiento-2020i.github.io/leccion-04-r-introduccion/).

## Bifuración y clonación de este documento
Ejecute los siguientes pasos para bifurcar a su cuenta en GitHub el repositorio que contiene este documento y posteriormente clonarlo a su computadora:

1. Bifurque (_fork_) el repositorio [https://github.com/geoprocesamiento-2020i/laboratorio-02-r-graficacion](https://github.com/geoprocesamiento-2020i/laboratorio-02-r-graficacion) a su cuenta personal en GitHub.
2. En el apartado _Settings_ del repositorio bifurcado a su cuenta, busque la sección _GitHub Pages_ y habilítela al seleccionar _master branch_ como fuente. Tome nota de la dirección web resultante (ej. https://mfvargas.github.io/laboratorio-02-r-graficacion-basica/).
3. En RStudio, clone el repositorio de su cuenta personal con la opción de menú _File - New Project - Version Control - Git_. En _Repository URL_ escriba la dirección de su repositorio (ej. https://github.com/mfvargas/laboratorio-02-r-graficacion-basica.git). Puede obtener esta dirección con el botón _Clone or download_, en la página principal del mismo repositorio.

## Desarrollo
1. 

## Actualización del repositorio en GitHub y la página en GitHub Pages